/**
 * Learned lean AI policy — GENERATED by simulator/src/distil-ai.ts.
 *
 * Distilled from the heavy lookahead AI (see that script). `WEIGHTS` scores the
 * generic action features the engine exposes; `CARD_BIAS` carries the
 * card-specific judgement generic features cannot express. Regenerate after
 * any card change — a stale bias is worse than none.
 */
export const POLICY_WEIGHTS: number[] = [0.8246,-1.1749,-0.439,-0.2833,-0.3588,0.8258,0.1501,0.2418,3.4151,1.9886,0.7414,1.416,-1.1449,1.1569,-0.9359,-1.4167,-2.9519,-6.7486,-2.8132,0.4335,-0.977,1.4282,-0.7981,0.1101,1.2666,2.7101,3.3335,0.5823,0.1359,-1.4827,-0.4786,-0.4064];

export const CARD_BIAS: Record<string, number> = {
  "embat-sagnant": 0.8251,
  "aguantar-el-cop": -0.9625,
  "atac-temerari": 0.4316,
  "entrar-en-furia": -0.13,
  "rugit-de-guerra": 0.3852,
  "escut-de-fusta": 0.0371,
  "roca-fosa": 0.2194,
  "pell-obsidiana": 1.2565,
  "gueiser": 0.3094,
  "riu-de-lava": -0.5341,
  "runa-fulla-esmolada": 0.1802,
  "cures-de-camp": 0.5001,
  "injeccio-adrenalina": 0.6388,
  "bomba-de-fum": 0.7823,
  "marca-de-la-perdicio": 0.348,
  "ma-de-la-tomba": -2.9786,
  "runa-confusio": -0.5014,
  "atac-llampec": 0.6116,
  "contraatac": 1.6766,
  "tall-precis": 1.4673,
  "estat-de-flux": -0.3113,
  "atac-encadenat": -0.1842,
  "cop-de-roca": -0.3948,
  "columna-de-terra": -0.4423,
  "mur-de-pedra": -0.7431,
  "preso-de-terra": -0.4165,
  "putrefaccio": -0.3031,
  "xuclar-la-vida": -0.9093,
  "invocar-ombra-infern": 0.3929,
  "ale-de-gebre": -0.8384,
  "paisatge-congelat": 0.5156,
  "desapareixer-en-lombra": -0.0572,
  "lligam-dombres": -1.4388,
  "granada-de-fragmentacio": 0.1928,
  "camp-minat": -2.7435,
  "traca-final": 2.8559,
  "runa-escut-invisible": 0.3815,
  "erupcio": 0.4115
};
